platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HomeWork' do
  # Pods for HomeWork
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'Core',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTText',
    'RCTventEmitter'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'HomeWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'HomeWork-tvOS' do
  # Pods for HomeWork-tvOS

  target 'HomeWork-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
